apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "app.example.com/v1alpha1",
          "kind": "AppService",
          "metadata": {
            "name": "example-appservice"
          },
          "spec": {
            "size": 3
          }
        }
      ]
    capabilities: Basic Install
  name: hello-operator.v0.0.1
  namespace: shall-workspace
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: AppService
      name: appservices.app.example.com
      displayName: Hello Operator
      description: Placeholder description
      version: v1alpha1
      specDescriptors:
        - description: The desired number of member Pods for the deployment.
          displayName: Name
          path: spec.name
          x-descriptors:
            - 'urn:alm:descriptor:com.tectonic.ui:label'
  description: Placeholder description
  displayName: Hello Operator
  install:
    spec:
      deployments:
      - name: hello-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: hello-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: hello-operator
            spec:
              containers:
              - command:
                - hello-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: hello-operator
                image: quay.io/shall3790/app-operator:v0.0.1
                imagePullPolicy: Always
                name: hello-operator
                resources: {}
              serviceAccountName: hello-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - hello-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - app.example.com
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: hello-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  replaces: hello-operator.v0.0.0
  version: 0.0.1
